"""Agregar campos ORCID y nombre_normalizado a autores

Revision ID: 7ed1430898ee
Revises: ef9a6cb3fd10
Create Date: 2025-12-12 12:18:20.124694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed1430898ee'
down_revision = 'ef9a6cb3fd10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orcid', sa.String(length=19), nullable=True))
        batch_op.add_column(sa.Column('nombre_normalizado', sa.String(length=250), nullable=True))
        batch_op.create_index(batch_op.f('ix_autores_nombre_normalizado'), ['nombre_normalizado'], unique=False)
        batch_op.create_unique_constraint('uq_autores_orcid', ['orcid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autores', schema=None) as batch_op:
        batch_op.drop_constraint('uq_autores_orcid', type_='unique')
        batch_op.drop_index(batch_op.f('ix_autores_nombre_normalizado'))
        batch_op.drop_column('nombre_normalizado')
        batch_op.drop_column('orcid')

    # ### end Alembic commands ###
