"""Migracion inicial - estructura completa del sistema

Revision ID: fa44e9f22476
Revises: 
Create Date: 2025-12-12 12:44:21.024901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa44e9f22476'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('orcid', sa.String(length=19), nullable=True),
    sa.Column('registro', sa.String(length=50), nullable=True),
    sa.Column('es_miembro_ca', sa.Boolean(), nullable=False),
    sa.Column('nombre_normalizado', sa.String(length=250), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('orcid')
    )
    with op.batch_alter_table('autores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_autores_nombre_normalizado'), ['nombre_normalizado'], unique=False)

    op.create_table('estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('indexaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('acronimo', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('prestigio', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('lgac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('paises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo_iso', sa.String(length=3), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_iso'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('propositos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipos_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('revistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('issn', sa.String(length=20), nullable=True),
    sa.Column('issn_electronico', sa.String(length=20), nullable=True),
    sa.Column('editorial', sa.String(length=200), nullable=True),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('area_tematica', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['paises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issn')
    )
    op.create_table('articulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('titulo_revista', sa.String(length=300), nullable=True),
    sa.Column('tipo_produccion_id', sa.Integer(), nullable=False),
    sa.Column('proposito_id', sa.Integer(), nullable=True),
    sa.Column('lgac_id', sa.Integer(), nullable=True),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('anio_publicacion', sa.Integer(), nullable=True),
    sa.Column('fecha_publicacion', sa.Date(), nullable=True),
    sa.Column('fecha_aceptacion', sa.Date(), nullable=True),
    sa.Column('revista_id', sa.Integer(), nullable=True),
    sa.Column('volumen', sa.String(length=20), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('pagina_inicio', sa.Integer(), nullable=True),
    sa.Column('pagina_fin', sa.Integer(), nullable=True),
    sa.Column('doi', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('issn', sa.String(length=20), nullable=True),
    sa.Column('nombre_congreso', sa.String(length=300), nullable=True),
    sa.Column('para_curriculum', sa.Boolean(), nullable=False),
    sa.Column('factor_impacto', sa.Float(), nullable=True),
    sa.Column('quartil', sa.String(length=5), nullable=True),
    sa.Column('citas', sa.Integer(), nullable=True),
    sa.Column('completo', sa.Boolean(), nullable=False),
    sa.Column('campos_faltantes', sa.Text(), nullable=True),
    sa.Column('archivo_origen', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['estados.id'], ),
    sa.ForeignKeyConstraint(['lgac_id'], ['lgac.id'], ),
    sa.ForeignKeyConstraint(['proposito_id'], ['propositos.id'], ),
    sa.ForeignKeyConstraint(['revista_id'], ['revistas.id'], ),
    sa.ForeignKeyConstraint(['tipo_produccion_id'], ['tipos_produccion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi')
    )
    op.create_table('revista_indexacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revista_id', sa.Integer(), nullable=False),
    sa.Column('indexacion_id', sa.Integer(), nullable=False),
    sa.Column('anio_indexacion', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['indexacion_id'], ['indexaciones.id'], ),
    sa.ForeignKeyConstraint(['revista_id'], ['revistas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revista_id', 'indexacion_id', name='uq_revista_indexacion')
    )
    op.create_table('articulo_autor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('es_corresponsal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos.id'], ),
    sa.ForeignKeyConstraint(['autor_id'], ['autores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('articulo_id', 'autor_id', name='uq_articulo_autor')
    )
    op.create_table('articulo_indexacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.Column('indexacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_verificacion', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos.id'], ),
    sa.ForeignKeyConstraint(['indexacion_id'], ['indexaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('articulo_id', 'indexacion_id', name='uq_articulo_indexacion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articulo_indexacion')
    op.drop_table('articulo_autor')
    op.drop_table('revista_indexacion')
    op.drop_table('articulos')
    op.drop_table('revistas')
    op.drop_table('tipos_produccion')
    op.drop_table('propositos')
    op.drop_table('paises')
    op.drop_table('lgac')
    op.drop_table('indexaciones')
    op.drop_table('estados')
    with op.batch_alter_table('autores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autores_nombre_normalizado'))

    op.drop_table('autores')
    # ### end Alembic commands ###
